import {
  computeBoxClassName,
  computeBoxProps,
  computeTwClass,
} from '@common/ui';
import { createElement } from 'react';

import type { BoxProps, DangerDoNotUse } from './types';

/**
 * ## Box
 *
 * The Box component serves as a wrapper component for most of the CSS utility
 * needs. It creates a new DOM element, a `<div>` by default that can be changed
 * with the `as` property. Let's say you want to use a `<span>` instead:
 *
 * Example:
 *
 * ```tsx
 * <Box as="span" m={1}>
 *   <Button />
 * </Box>
 * ```
 *
 * This works great when the changes can be isolated to a new DOM element.
 * For instance, you can change the margin this way.
 *
 * However, sometimes you have to target the underlying DOM element.
 * For instance, you want to change the text color of the button. The Button
 * component defines its own color. CSS inheritance doesn't help.
 *
 * To workaround this problem, the Box children accept a render props function.
 * This way, `Button` can pull out the `className` generated by the `Box`.
 *
 * Example:
 *
 * ```tsx
 * <Box color="primary">{(props) => <Button {...props} />}</Box>
 * ```
 *
 * ## Box Units
 *
 * `Box` units, like width, height and margins can be defined in two ways:
 *
 * - By plain numbers
 *   - 1 unit equals `1rem` for width, height and positioning properties.
 *   - 1 unit equals `0.5rem` for margins and paddings.
 * - By strings with proper CSS units
 *   - For example: `100px`, `2em`, `1rem`, `100%`, etc.
 *
 * If you need more precision, you can always use fractional numbers.
 *
 * Default font size (`1rem`) is equal to `12px`.
 *
 * - [View documentation on tgui core](https://tgstation.github.io/tgui-core/?path=/docs/components-box--docs)
 */
export function Box<TElement = HTMLDivElement>(
  props: BoxProps<TElement> & DangerDoNotUse,
) {
  const { as = 'div', className, children, tw, ref, ...rest } = props;

  const computedClassName = className
    ? `${className} ${computeBoxClassName<TElement>(rest)}`
    : computeBoxClassName<TElement>(rest);

  const computedProps = computeBoxProps({
    ...rest,
    ...computeTwClass(tw),
  });

  return createElement(
    as,
    {
      ...computedProps,
      ref: ref,
      className: computedClassName,
    },
    children,
  );
}
