name: Setup Bun with Cache
description: Installs Bun
runs:
  using: "composite"
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
